# Generated by Django 3.2 on 2021-07-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemperaturesByCity',
        ),
    ]
