# Generated by Django 3.2 on 2021-07-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_test', '0002_delete_temperaturesbycity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaturesByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=10)),
                ('averagetemperature', models.DecimalField(decimal_places=10, max_digits=12)),
                ('averagetemperatureuncertainty', models.DecimalField(decimal_places=10, max_digits=12)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
    ]
